### ISSUE TITLE
There is no way to use custom config location

### ISSUE THREAD

**Issue by brejoc** [RaymiiOrg/NoPriv#20]
Right now the config has to be at the predefined locations. If you want to backup several email accounts with one cronjob or script this is not very convenient. The user should be able to pass the location of an alternate config to nopriv. Something like "nopriv -c ../myconfigs/xyz-account.ini".

What do you think?

**Comment by jmserra** [comment]
That would be great to have, but i guess then the output folder should be different as well, as otherwise if you execute twice the script with different configs at the same time it will be overwritten

**Comment by brejoc** [comment]
Cleaning up. If you think this should be re-opened, feel free to do so or contact me.
